[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "af4NQwyYFtEinXkxppHbpj9aAWNC5bhJG1qJ1Fiyx2B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rnajera/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
